apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-app
  template:
    metadata:
      labels:
        app: pizza-app
    spec:
      containers:
      - name: pizza-app
        image:  vladkarpets/pizza-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-app-service
spec:
  selector:
    app: pizza-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
